version: '3.4'

services:
  db:
    user: "${UID:-1000}"
    image: postgres:11.6
    volumes:
      - ./shared/postgresql:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.postgres
    environment:
      # We set PGDATA to a subfolder because Postgres needs this folder to be
      # empty, and we have a .gitkeep file there
      - PGDATA=/var/lib/postgresql/data/pgdata
  app:  &app
    user: "${UID:-1000}"
    container_name: orm-blog-app
    build:
      network: host
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: "${UID:-1000}"
        DEV_MODE: 1
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    command: /start-runserver.sh
    volumes:
      - ./backend:/app
      - ./shared/media:/app/shared/media
      - ./shared/static:/app/shared/static
      - ./shared/templates:/app/shared/templates


  redis:
    image: redis:3.0

  celeryworker:
    <<: *app
    container_name: orm-blog-celeryworker
    depends_on:
      - redis
      - db
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    <<: *app
    container_name: orm-blog-celerybeat
    depends_on:
      - redis
      - db
    ports: []
    command: /start-celerybeat.sh

  flower:
    <<: *app
    container_name: orm-blog-flower
    ports:
      - "5555:5555"
    command: /start-flower.sh
